language: python
python: 2.7
sudo: false
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - python -m pip install -U pip virtualenv
  - python -m virtualenv .
# Keep in sync with buildout.cfg:
  - bin/python bootstrap.py --setuptools-version=38.2.4 --buildout-version=2.11.3
install:
  - bin/python -V
  - bin/buildout -Nvt 5 -c travis.cfg annotate
  - bin/buildout -Nvt 5 -c travis.cfg
script:
  - bin/test
